permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: yarn install --immutable

      - run: yarn run format
      - run: yarn run lint
      - run: yarn run check

      - run: yarn run build

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './build'

      - id: deployment
        uses: actions/deploy-pages@v2

on:
  push:
    branches:
      - main
  workflow_dispatch:
